/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_HelloNDK */

#ifndef _Included_com_example_jnitest_HelloNDK
#define _Included_com_example_jnitest_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_HelloNDK
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_HelloNDK_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
